FROM condaforge/mambaforge

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV TZ=Europe/Berlin
ENV TERM xterm-256color
ARG N_JOBS=8
ARG PYTHON_VERSION=3.6
ENV PYTHON_VERSION=$PYTHON_VERSION
ENV N_JOBS=$N_JOBS
ENV MAKEFLAGS=-j${N_JOBS}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y --no-install-recommends --allow-unauthenticated apt-utils
RUN apt-get install -y --no-install-recommends --allow-unauthenticated \
    zip \
    gzip \
    make \
    automake \
    gcc \
    build-essential \
    g++ \
    cpp \
    libc6-dev \
    man-db \
    autoconf \
    pkg-config \
    unzip \
    libffi-dev \
    software-properties-common \
    libhdf5-serial-dev \
    hdf5-tools \
    libhdf5-dev

RUN mkdir /fever
WORKDIR /fever

ADD requirements.txt /fever/

RUN mamba install --yes python=$PYTHON_VERSION               # 'setuptools<=56.1.0'
RUN mamba create --yes -n fever python=$PYTHON_VERSION       # 'setuptools<=56.1.0'
SHELL ["bash", "-lc"]
ENV PATH /opt/conda/envs/fever/bin:$PATH



RUN /bin/bash -c "source activate fever"
RUN pip install --build-option=--jobs=$N_JOBS --install-option=--jobs=$N_JOBS -r requirements.txt

RUN python -c "import nltk; nltk.download('punkt')"

RUN mkdir -pv src
RUN mkdir -pv configs

ADD src src
ADD configs configs

ADD predict.sh .

ENV PYTHONPATH src
ENV FLASK_APP sample_application:my_sample_fever

#ENTRYPOINT ["/bin/bash","-c"]
CMD ["waitress-serve", "--host=0.0.0.0", "--port=5000", "--call", "sample_application:my_sample_fever"]
